# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Jinli CV"
license = "MIT"
licenselink = "https://github.com/jin-li/jinli-cv/blob/master/LICENSE"
description = "Theme to build a customizeable printable CV with multi-language support. Fork of Almeida CV by Inês Almeida."
homepage = "https://github.com/jin-li/jinli-cv"
tags = ["cv", "resume", "minimal", "simple", "multi-language"]
features = ["simple", "cv", "printable", "multi-language"]
min_version = "0.41.0"

[author]
  name = "Jin Li"
  homepage = "https://jinli.io"
